### ISSUE TITLE
Installation failed?

### ISSUE THREAD

**Issue by reimax** [Riimu/Kit-CSRF#2]
download and install:

root@ubuntu: /CSRF/ php -r "readfile('https://getcomposer.org/installer');" | php
# !/usr/bin/env php

All settings correct for using Composer
Downloading...

Composer successfully installed to: /CSRF/composer.phar
Use it: php composer.phar
root@ubuntu:/CSRF# php composer.phar require riimu/kit-csrf:2.*
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package riimu/kit-csrf No version set (parsed as 1.0.0) could not be found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by Riimu** [comment]
Looks like there was a small mistake in the installation instructions. The package name in `php composer.phar require riimu/kit-csrf:2.*` should probably be in quotes, since some shells interpret the \* as a path wildcard.

Try and see if running `php composer.phar require "riimu/kit-csrf:2.*"` works instead

**Comment by reimax** [comment]
php composer.phar require "riimu/kit-csrf:2.*"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package riimu/kit-csrf No version set (parsed as 1.0.0) could not be found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by Riimu** [comment]
Hmm.. Maybe there is something conflicting in your `composer.json` file, can you please paste that here.

**Comment by reimax** [comment]
I use the original file unchanged. download archives again:

php composer.phar require "riimu/kit-csrf:2.*"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package riimu/kit-csrf No version set (parsed as 1.0.0) could not be found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by Riimu** [comment]
Then, I assume it's the same issue as described here: https://github.com/fruux/sabre-vobject/issues/221

You're note supposed to copy the composer.json file from the package you are trying to copy.  To install the package all you need to do, for example, is the create a new empty directory and simply run the two following commands:

```
php -r "readfile('https://getcomposer.org/installer');" | php
php composer.phar require "riimu/kit-csrf:2.*"
```

There is absolutely no need for you to create the composer.json file yourself or copy it from the repository. The composer itself creates the file for you. If you copy the composer.json from this repository, it will create conflicts because it contains the dependencies for this project and not the one you are creating.

**Comment by reimax** [comment]
now its work. install script.

i use Sessions:
require_once('/class/CSRF/vendor/autoload.php');
$csrf = new \Riimu\Kit\CSRF\CSRFHandler(false);

in form i add csrf_token field. send form and see:
print_r($_SESSION);
Array
(
    [csrf_token] => CZvyWUZ2G6w9C5K7CbWeSKNKIuTmsR38f8FKI/r24Rk=
)
print_r($_REQUEST);
Array
(
     [csrf_token] => CZvyWUZ2G6w9C5K7CbWeSKNKIuTmsR38f8FKI/r24Rk=
)

code 
try {
    $csrf->validateRequest(true);
} catch (\Riimu\Kit\CSRF\InvalidCSRFTokenException $ex) {
    header('HTTP/1.0 400 Bad Request');
    exit('Bad CSRF Token!');
}

return Bad CSRF Token!. session == request.
